#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2016 Intel Corp.
#
"""
Main Module to call Control CLI.
"""
from control.cli.control_cli import CtrlCliExecutor

if __name__ == '__main__':
    CtrlCliExecutor().execute_cli_cmd()
