#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright (c) 2016 Intel Corp.
#
"""
Main Module to call Control CLI.
"""
from control.cli.control_cli import ControlCommandLineInterface
from sys import exit

if __name__ == '__main__':
    return_value = ControlCommandLineInterface().execute_cli_cmd()
    exit(return_value)
