#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Copyright (c) 2016 Intel Corp.
#
"""
Main Module to call Control CLI.
"""
from control.cli.control_cli import ControlCommandLineInterface
from sys import exit

if __name__ == '__main__':
    try:
        return_value = ControlCommandLineInterface().execute_cli_cmd()
        exit(return_value)
    except KeyboardInterrupt:
        print('Exiting : On KeyBoard Interrupt')
        exit(1)
